# Aquarius - Automation Simplified
#
# @brief Git script for exporting PCB data for the repo.
# @note runs manually or automatically when there is a release
# @date 10/29/25
# @author cyberreefguru
# (c) CRG Makes 2025
name: Aquarius-Env-Module-Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call-export-pcb:
    uses: crgmakes/kicad-extras/.github/workflows/crgm-ecad-release.yaml@main
    with:
      name: 'Environment Module'
      repo-name: module-environment
      file-name: environment-module
